### ISSUE TITLE
FlutterActivity Error on Android Device

### ISSUE THREAD

**Issue by rudineiziliodb1** [usabilla/usabilla-u4a-flutter#18]
When using the plugin and emulating on an Android device, the following error is occurring in the attachment, causing the campaign to not be displayed.

On IOS it works normally.

```
I[/flutter]() (17880): PlatformException(error, io.flutter.embedding.android.FlutterActivity cannot be cast to androidx.fragment.app.FragmentActivity, null, java.lang.ClassCastException: io.flutter.embedding.android.FlutterActivity cannot be cast to androidx.fragment.app.FragmentActivity

I[/flutter]() (17880): 	at com.usabilla.flutter_usabilla.FlutterUsabillaPlugin.initialize(FlutterUsabillaPlugin.kt:150)
I[/flutter]() (17880): 	at com.usabilla.flutter_usabilla.FlutterUsabillaPlugin.onMethodCall(FlutterUsabillaPlugin.kt:104)
I[/flutter]() (17880): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
I[/flutter]() (17880): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
I[/flutter]() (17880): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:320)
I[/flutter]() (17880): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I[/flutter]() (17880): 	at android.os.Handler.handleCallback(Handler.java:938)
I[/flutter]() (17880): 	at android.os.Handler.dispatchMessage(Handler.java:99)
```

**Comment by rudineiziliodb1** [comment]
My project was without the MainActivity file in the Android folder, after several tests I managed to solve it just by adding it.
